name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/mi-skam/devcontainers-dev1
        cacheFrom: ghcr.io/mi-skam/devcontainers-dev1
        push: always

      
    
    
      
